const js_mappingVisitor = require('../generated/js_mappingVisitor').js_mappingVisitor;

/**
 * This Visitor walks the tree generated by parsers and produces Python code
 *
 * @returns {object}
 */
class Visitor extends js_mappingVisitor {
  /**
   * Entry point of tree visiting
   *
   * @param {object} ctx
   * @returns {string}
   */
  start(ctx) {
    return this.visitStructureMap(ctx);
  }
}

module.exports = Visitor;
